### ISSUE TITLE
'RuntimeError: CUDA error: device-side assert triggered' when dataset config is changed

### ISSUE THREAD

**Issue by alessandrosimon** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#2]
Hi, when I change the parameters:
max_len -> 24, max_ops -> 10 and the number of variables -> 6
I get a runtime error for the embedding layer:

```
[...]
/tmp/pip-req-build-h953rg2q/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [200,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[...]
File "code/NeuralSymbolicRegressionThatScales/src/nesymres/architectures/model.py", line 101, in forward
    pos = self.pos_embedding(
  File "miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 145, in forward
    return F.embedding(
  File "miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/functional.py", line 1913, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
```

I tried changing the variable length_eq in config.yaml but then I get a tensor size mismatch error. Should have something to do with the network sampling equations that are larger than it expected, as sometimes I reach 5 or 6 epochs before encountering the error.

**Comment by TommasoBendinelli** [comment]
Hi Alessandro,
We haven't test training with more that three indepedent variables, so I am not 100% sure. I suspect that it occurs when you are sampling an equation that is larger than the pos_embedding maximum size. Try to increase output_dim in the config.yaml to a bigger number. Let me know if this helps

**Comment by alessandrosimon** [comment]
Hi Tommaso,
thanks for the feedback!
I tried both output_dim = 120 and 140 but still get errors, unfortunately. The latest run gave me this error:
```
  File "code/NeuralSymbolicRegressionThatScales/src/nesymres/architectures/model.py", line 99, in forward
    enc_src = self.enc(encoder_input)
  File "miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "code/NeuralSymbolicRegressionThatScales/src/nesymres/architectures/set_encoder.py", line 62, in forward
    x = x.view(x.shape[0],x.shape[1],-1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 352, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by TommasoBendinelli** [comment]
Okey this is a somewhat different error. It means that batch is empty. In the __getitem__ method in src/nesymres/architectures/data.py there are some try and except we perform for each equation. Sometimes, since the equation generation is random it might happen that the equation is somewhat invalid and so we are dropping it at this point. In your case it appears that all equation in a given batch are invalid. Is this happening at first iteration or after some times? I would try to increase the batch size and see if it still happens

**Comment by alessandrosimon** [comment]
The errors always happen after some time, but I'll try increasing the batch size

**Comment by gibipara92** [comment]
Just chiming in, another option to consider would be to change that try-except part of the code, to ensure that every batch is full (e.g. by sampling a new equation when the previous one was invalid). This might even help stabilize training, if it otherwise occurs often to get almost-empty batches (and therefore noisier grads).

**Comment by TommasoBendinelli** [comment]
Yeah, it could be a good solution! If you implement it, please create a git pull. I will be happy to test it and merge into the branch

**Comment by alessandrosimon** [comment]
I tried my luck with a larger batch size and it's working now.
Thanks!
